#!/bin/bash

url=https://weathered-breeze-1152.a9ito.workers.dev/ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache.tar.gz
echo "unzip done"
find ccache.tar.gz -delete
